[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[env]
ESP_HAL_CONFIG_PLACE_RMT_DRIVER_IN_RAM = "true"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C",
  "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"
# target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]

[rust-analyzer]
cargo.noDefaultFeatures = true
cargo.features = ["esp32c6"]
# cargo.features = ["esp32s3"]
